import Head from 'next/head'
import Image from 'next/image'
import { Open_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const roboto = Open_Sans({
  weight: '600',
  subsets: ['latin'],
})

const roboto2 = Open_Sans({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{textAlign: "center"}}>
          <h1 className={roboto.className} style={{fontSize: "34px", marginBottom: 2}}>Hold tight! We are filling up our 🔋</h1>
          <p className={roboto2.className} style={{opacity: 0.8}}>Or in other words: We are currently actively developing this website to reveal our plans to the world.</p>
        </div>
      </main>
    </>
  )
}
